export const FIND_UNITS = 'FIND_UNITS';
export const SET_TRAINING_TIME = 'SET_TRAINING_TIME';
export const SET_INCLUDE_UNITS_CLOSED = 'SET_INCLUDE_UNITS_CLOSED';
export const RESET_FIELDS = 'RESET_FIELDS';
